USE [DBNAME]
GO
GRANTDENYREVOKE CREATE SEQUENCE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE DELETE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE EXECUTE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE INSERT ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE REFERENCES ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE SELECT ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE UPDATE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE VIEW CHANGE TRACKING ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE VIEW DEFINITION ON SCHEMA::[SCHEMA] TO [ROLE]
GO
---------WARNING
USE [DBNAME]
GRANTDENYREVOKE ALTER ON SCHEMA::[SCHEMA] TO [ROLE]
GO
USE [DBNAME]
GO
GRANTDENYREVOKE TAKE OWNERSHIP ON SCHEMA::[SCHEMA] TO [ROLE]
GO
GO
USE [DBNAME]
GO
GRANTDENYREVOKE CONTROL ON SCHEMA::[SCHEMA] TO [ROLE]
GO