use [DBNAME]
GO
GRANTDENYREVOKE ALTER ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE CONTROL ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE CREATE SEQUENCE ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE DELETE ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE EXECUTE ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE INSERT ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE REFERENCES ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE SELECT ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE TAKE OWNERSHIP ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE UPDATE ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE VIEW CHANGE TRACKING ON SCHEMA::[DEL] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE VIEW DEFINITION ON SCHEMA::[DEL] TO [ROLE]
GO
