use [DBNAME]
GO
GRANTDENYREVOKE ALTER ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE CONTROL ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE CREATE SEQUENCE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE DELETE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE EXECUTE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE INSERT ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE REFERENCES ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE SELECT ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE UPDATE ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE VIEW CHANGE TRACKING ON SCHEMA::[SCHEMA] TO [ROLE]
GO
use [DBNAME]
GO
GRANTDENYREVOKE VIEW DEFINITION ON SCHEMA::[SCHEMA] TO [ROLE]
GO
---------WARNING
use [DBNAME]
GO
GRANTDENYREVOKE TAKE OWNERSHIP ON SCHEMA::[SCHEMA] TO [ROLE]
GO