CREATE ROLE DDWrite;
GRANT INSERT, UPDATE, DELETE ON SCHEMA::DD TO DDWrite;


CREATE ROLE DDRead;
GRANT SELECT,  EXECUTE ON SCHEMA::DD TO DDRead;

CREATE ROLE DDBuild;
GRANT ALTER, REFERENCES, VIEW DEFINITION ON SCHEMA::DD TO DDBuild;

CREATE ROLE DDAdmin;
GRANT TAKE OWNERSHIP, CONTROL ON SCHEMA::DD TO DDAdmin;


ALTER ROLE DDAdmin ADD MEMBER DDWrite;
ALTER ROLE DDAdmin ADD MEMBER DDRead;
ALTER ROLE DDAdmin ADD MEMBER DDBuild;